### ISSUE TITLE
bluetooth mac address

### ISSUE THREAD

**Issue by twu2** [arttttt/android_device_xiaomi_mocha1#2]
in conn_init.c, it set bluetooth to persist.service.bdroid.bdaddr, but the address end with LF (0x0a), maybe it should remove this.
and even it set the mac here, the system still get a different bluetooth mac address, and it might change sometimes.

so, could you also change init.comms.rc, replace /mnt/factory/bluetooth/bt_mac.txt with /data/bt_mac.txt. then we can force to load the correct bluetooth mac address from /data/bt_mac.txt

**Comment by arttttt** [comment]
The problem was bigger than you thought, but I fixed it.
